@startuml

state "<b>Opened</b>" as Opened
Opened: * ""Amount""
Opened: * ""Snapshot""
Opened: * ""Period""

state "<b>Closed</b>" as Closed
Closed: * ""Amount""
Closed: * ""Squash""
Closed: * ""Timeout""
Closed: * ""Pend""

state "<b>Responded</b>" as Responded
Responded: * ""Amount""
Responded: * ""Pend""
Responded: * ""Pend""

state "<b>Elapsed</b>" as Elapsed
Elapsed: * ""Pend""

state "<b>Resolved</b>" as Resolved
Resolved: * ""Pend""
Resolved: * ""Pend""

[*] --> Opened : <b>open</b>\nby opener
note on link
  * In all stages we keep a tuple of verification keys.
  * The initial order of keys is `(opener, non-opener)`.
  * The `Amount` reflects the opener balance.
  * The `Total - Amount` is the non-opener balance.
end note
Opened --u-> Opened : ""<b>add</b>""
Opened --> Closed : <b>close</b>\nby closer
note on link
  * Doesn't release assets.
  * The order of keys changes to `(closer, non-closer)`.
  * Optionally delivers the newest snapshot.
  * The `Amount` reflects the closer balance after
  incorporating differences from the snapshot's squashes.
end note
Closed --u-> Closed : <b>free</b>\nby closer
Closed --d-> Responded : <b>respond</b>\nby non-closer
note on link
  * Releases account assets.
  * The left over should cover the closer account
  and potential liabilities of the non-closer
end note

Closed --d-> Elapsed : <b>elapse</b>\nby closer
note on link
  * Releases account assets.
  * For simplicity we disallow the closer to provide
  cheques owned by the non-closer.
  * The left over should cover just the
  non-closer account as any extra liabilities
  of the closer were ignored.
end note

Responded --u-> Responded : <b>free</b>\nby non-closer
Responded --d-> Resolved : <b>resolve</b>\nby closer
note on link
  * Releases account assets.
end note
Responded --> [*] : <b>end</b>\nby closer

Elapsed --u-> Elapsed : <b>free</b>\nby closer
Elapsed --d-> Resolved : <b>resolve</b>\nby non-closer
note on link
  * Releases account assets.
  * Non-closer `Pend` is empty.
end note
Elapsed --d-> [*] : <b>end</b>
note on link
  * Possibly releases account
  assets to non-closer.
end note

Resolved --u-> Resolved : <b>free</b>
Resolved --> [*] : <b>end</b>

@enduml
